import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/general/theme-provider";

const nunito = localFont({
  variable: "--font-nunito",
  src: [
    {
      path: "../fonts/Nunito-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "../fonts/Nunito-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
  display: "swap",
  weight: "variable",
  fallback: ["ui-sans-serif", "system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}  suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
